# .github/workflows/publish.yml

# 工作流名称：发布到 PyPI
name: Publish to PyPI

# 触发条件：推送以 v 开头的标签时触发
on:
  push:
    tags:
      - 'v*'  # 例如: v1.0, v2.1.0

# 任务定义
jobs:
  # 发布任务
  publish:
    # 运行环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出代码
      # 将仓库代码下载到工作环境
      - uses: actions/checkout@v4

      # 步骤 2: 设置 Python 环境
      # 安装指定版本的 Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 步骤 3: 安装 uv 工具
      # 现代化的 Python 包管理工具
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      # 步骤 4: 构建包
      # 生成源代码发行版和轮子文件
      - name: Build package
        run: uv build

      # 步骤 5: 发布到 PyPI
      # 自动构建并上传包到 PyPI
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
